version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.app
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/usr/src/app/
      - ./db_backup:/home/db_backup/
    ports:
      - 8001:8000
    env_file:
      - ./.env.dev
    networks:
      - app-network

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - ./database:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pms
      - POSTGRES_PASSWORD=pms
      - POSTGRES_DB=pms
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pms"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge